# permissions to do viewer runnerpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerpool-viewer-role
rules:
- apiGroups:
  - github.juan-lee.dev
  resources:
  - runnerpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.juan-lee.dev
  resources:
  - runnerpools/status
  verbs:
  - get
