# permissions to do edit runnerpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerpool-editor-role
rules:
- apiGroups:
  - github.juan-lee.dev
  resources:
  - runnerpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.juan-lee.dev
  resources:
  - runnerpools/status
  verbs:
  - get
  - patch
  - update
